### ISSUE TITLE
Add support to specify protocol during git clone

### ISSUE THREAD

**Issue by cbirajdar** [linuxhq/ansible-role-git#1]
As per [documentation](http://docs.ansible.com/ansible/latest/git_module.html#options) for ansible git module, repo attribute allows specifying different protocols during clone - git vs SSH vs HTTP(S). Can we add an optional key - protocol (defaults to https) to support it?

@tkimball83 What do you think? I can send a PR with this change.

```
git_repos:
  ansible-role:
    org: linuxhq
    server: github.com
    protocol: git
```

P.S. Awesome work on creating these ansible roles.
